version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - cmd: npm prune
  - cmd: npm install
  - cmd: npm install jspm -g
  - cmd: npm install typescript -g
  - cmd: npm install gulp -g
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore CITesting.csproj --verbosity m
  - cmd: jspm clean
  - cmd: jspm install
  - cmd: npm run minify-css
  - cmd: tsc
  - cmd: gulp bundle
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish CITesting.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\bin\Debug\netcoreapp1.1\publish'
   name: CITesting
   type: WebDeployPackage
clone_depth: 1
test_script:
  # restore packages for our unit tests
  #- cmd: dotnet restore ./tests/tests.csproj --verbosity m
  # run the unit tests (requires changing into the test directory)
  #- cmd: cd tests
  #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
  #app veyor tyest
deploy: off